# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify the installation

    - name: Set executable permissions for entry_point.sh
      run: |
        chmod +x ./entry_point.sh  # Adjust the path as necessary

    - name: Set up Docker
      run: |
        # Build and start containers
        docker-compose up -d --build
        # Wait for Docker services to be up and running
        sleep 15
        # Check the running containers
        docker-compose ps

    - name: Check Locust Container Logs
      run: |
        docker-compose logs locust-container

    - name: Run Pytest inside Docker
      run: |
        docker exec locust-container pytest

    - name: Shut down Docker containers
      run: |
        docker-compose down        
